# server properties
server:
 port: 8083

# spring properties
spring:
 h2:
    console:
      enabled: true
 datasource:
    url: jdbc:h2:mem:pensioner_detail_db
      
    username: sa
    password: 
    driver-class-name: org.h2.Driver
 jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
 application:
  name: PENSIONER-DETAIL-SERVICE
 
 
#Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # add public IP link here
      defaultZone: http://localhost:8761/eureka/ 

# Error Messages
errorMessage: Aadhaar Number Not Found